apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-count
  labels:
    app.kubernetes.io/managed-by: java
    app.kubernetes.io/name: word-count
    app.kubernetes.io/version: '1.0'
    app.kubernetes.io/part-of: word-count-app
    app.openshift.io/runtime: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: word-count
      app.kubernetes.io/version: '1.0'
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: java
        app.kubernetes.io/version: '1.0'
        app.kubernetes.io/name: word-count
        app.openshift.io/runtime: java
    spec:
      containers:
      - name: word-count
        image: word-count:1.0
        resources:
          limits:
            cpu: '300m'
            memory: 300Mi
          requests:
            cpu: '100m'
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: word-count-env
        imagePullPolicy: Always
