apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base/01_topics.yaml
- ./base/02_word-gen-deployment.yaml
- ./base/03_word-count-deployment.yaml

commonLabels:
  app: word-count

configMapGenerator:
- name: word-count-env
  literals:
  - KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap:9092
  - GEN_SLEEP=50
  options:
    disableNameSuffixHash: true
