apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-connector
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    # database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    # database.history.kafka.topic: mysql.schema-changes.inventory
    database.hostname: mysql.debezium.svc.cluster.local
    database.allowPublicKeyRetrieval: true
    database.port: 3306
    database.user: debezium
    database.password: dbzpwd
    database.dbname: inventory
    database.server.name: inventory_connector_mysql
    # database.include.list: public.inventory
